### ISSUE TITLE
how to make the download system post a new topic in a set cat after upload

### ISSUE THREAD

**Issue by wullien** [oxpus/Download-Extention#17]
is there any way to set the system to post a new topic for every new upload posted?

i have tried to login to your oxpus site but it wont let me use my userr or pass to login

**Comment by oxpus** [comment]
Take a look into the general settings on the ext (ACP).
There you can enable forum topics for each download.

**Comment by wullien** [comment]
thanks new seen that part :P 
i have 1 more problem its the downloads page them selfs look like the attached photo any help would be good
![bbdlz](https://cloud.githubusercontent.com/assets/13025078/8836783/d7e20a5a-30ba-11e5-922f-0b9636df4f00.jpg)
