### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by TWEagle** [oxpus/Download-Extention#19]
SQL ERROR [ mysql4 ]

Table 'k127980_all.o_dl_versions' doesn't exist [1146]

SQL

SHOW COLUMNS FROM o_dl_versions

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 855
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysql.php
LINE: 181
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysql->sql_query()

FILE: [ROOT]/phpbb/db/tools.php
LINE: 1163
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/phpbb/db/tools.php
LINE: 1185
CALL: phpbb\db\tools->sql_list_columns()

FILE: [ROOT]/phpbb/db/tools.php
LINE: 794
CALL: phpbb\db\tools->sql_column_exists()

FILE: (not given by php)
LINE: (not given by php)
CALL: phpbb\db\tools->perform_schema_changes()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 550
CALL: call_user_func_array()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 496
CALL: phpbb\db\migrator->run_step()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 305
CALL: phpbb\db\migrator->process_data_step()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 262
CALL: phpbb\db\migrator->try_apply()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 262
CALL: phpbb\db\migrator->try_apply()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 202
CALL: phpbb\db\migrator->try_apply()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 185
CALL: phpbb\db\migrator->update_do()

FILE: [ROOT]/phpbb/extension/base.php
LINE: 80
CALL: phpbb\db\migrator->update()

FILE: [ROOT]/phpbb/extension/manager.php
LINE: 187
CALL: phpbb\extension\base->enable_step()

FILE: [ROOT]/includes/acp/acp_extensions.php
LINE: 177
CALL: phpbb\extension\manager->enable_step()

FILE: [ROOT]/includes/functions_module.php
LINE: 674
CALL: acp_extensions->main()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()

**Comment by oxpus** [comment]
Did you installed the extension as new or as update?

**Comment by oxpus** [comment]
Any answer will be welcome ;-)

**Comment by oxpus** [comment]
No answer, so this can be closed...
